name: Feature Request
description: Request a new Feature.
title: "[Feature]: "
labels: ["feature"]
projects: ["Cobas91/3"]
body:
  - type: markdown
    attributes:
      value: |
        Explain the feature in detail.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your feature.
    validations:
      required: true
